[main]
font=Hack Nerd Font Mono:size=24
icons-enabled=true
prompt=""
line-height=60
fields=name,generic,comment,categories,filename,keywords
terminal=kitty -e
layer=overlay
lines=10
width=25

[colors]
# Kanagawa "Wave" Palette
background = 1F1F28FF
text = DCD7BAFF
match = FF9E3BFF
placeholder = 727169FF
selection = 223249FF
selection-text = DCD7BAFF
selection-match = D27E99FF

[border]
radius=0
width=0

[key-bindings]
delete-line-forward = none
next = Down Control+j
prev = Up Control+k
next-page = Shift+j
prev-page = Shift+k
