[main]
font=JetBrainsMono Nerd Font:size=28
icons-enabled=true
prompt=""
line-height=50
fields=name,generic,comment,categories,filename,keywords
terminal=kitty -e
layer=overlay
lines=10
width=25

[colors]
# Tokyo Night Storm
background=1f2335ff
text=c0caf5ff
match=2ac3deff
selection=363d59ff
selection-match=2ac3deff
selection-text=c0caf5ff
border=29a4bdff

[border]
radius=0
width=0

[key-bindings]
delete-line-forward = none
next = Down Control+j
prev = Up Control+k
next-page = Shift+j
prev-page = Shift+k
