#!/usr/bin/env bash

DOTFILES_DIR="$HOME/dotfiles/config"
CONFIG_DIR="$HOME/.config"
DIRS=("foot" "fuzzel" "hypr" "lf" "lsd" "nvim" "river" "tmux" "waybar")

for dir in "${DIRS[@]}"; do
	SRC="$DOTFILES_DIR/$dir"
	DEST="$CONFIG_DIR/$dir"

	if [ -L "$DEST" ] || [ -d "$DEST" ]; then
		echo "Removing existing $DEST..."
		rm -rf "$DEST"
	fi

	echo "Linking $SRC -> $DEST"
	ln -s "$SRC" "$DEST"
done

echo "All dotfiles have been symlinked!"
