wallpaper {
	monitor = DP-1
	# path = ~/Pictures/Wallpapers/ign_unsplash23.png
	path = ~/Pictures/Wallpapers/5amtrain.jpg
	fit_mode = cover
}

wallpaper {
	monitor = HDMI-A-2
	# path = ~/Pictures/Wallpapers/dog.jpg
	# path = ~/Pictures/Wallpapers/stawa.png
	# path = ~/Pictures/Wallpapers/1700205347696635.jpg
	path = ~/Pictures/Wallpapers/ign_unsplash23.png
	fit_mode = cover
}

splash = false
