wallpaper {
	monitor = DP-1
	# path = ~/Pictures/Wallpapers/ghibli-japanese-walled-garden.png
	path = ~/Pictures/Wallpapers/koi1.jpg
	fit_mode = cover
}

wallpaper {
	monitor = HDMI-A-2
	path = ~/Pictures/Wallpapers/dog.jpg
	fit_mode = cover
}

splash = false
