preload = ~/Pictures/Wallpapers/ghibli-japanese-walled-garden.png
preload = ~/Pictures/Wallpapers/dog.jpg

wallpaper = DP-1,~/Pictures/Wallpapers/ghibli-japanese-walled-garden.png
wallpaper = HDMI-A-2,~/Pictures/Wallpapers/dog.jpg
