[mgr]
syntect_theme = "/home/dillon/.config/yazi/gruvbox.tmTheme"

# Border
border_symbol = " "

[status]
# overall   = { fg = "#c0caf5", bg = "#1f2335" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Completion
[cmp]
icon_file    = ""
icon_folder  = ""
icon_command = ""

# Which
[which]
cols            = 3
separator       = " ➜ "

# Confirm
[confirm]
content = {}
list    = {}
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Notify
[notify]
icon_error = ""
icon_warn = ""
icon_info = ""
