# font = JetBrainsMono Nerd Font:size=15
font = Hack Nerd Font:size=15
# font = Iosevka Nerd Font Mono:size=17.5

[main]
# term=xterm-256color
# include=/usr/share/foot/themes/tokyonight-night
# include=/usr/share/foot/themes/tokyonight-storm
# include=/usr/share/foot/themes/kanagawa
include=/usr/share/foot/themes/gruvbox
# include=/usr/share/foot/themes/onedark
# include=/usr/share/foot/themes/nord
# include=/usr/share/foot/themes/gruvbox-dark
